### ISSUE TITLE
Center "x" button in find box

### ISSUE THREAD

**Issue by raderio** [jenkins-contrib-themes/jenkins-neo-theme#3] opened 2016-02-10 09:27 UTC
Center "x" button in find box

![find_x_button](https://cloud.githubusercontent.com/assets/4563564/12943340/47640680-cfe9-11e5-83d5-b2a88111a271.png)

Chrome Version 44.0.2403.89

**Comment by aarjithn** [comment] 2016-02-10 16:18
Thanks, I've noticed it. Will look into this.

**Comment by RockyMM** [comment] 2016-02-12 10:20
Hey, my colleague and me have _fiddled_ with CSS3 to create pure CSS 'X'. Take a look:
[JSFiddle](https://jsfiddle.net/gbnegqse/4/#&togetherjs=6P2FOzEU5t)

**Comment by aarjithn** [comment] 2016-02-21 00:16
@RockyMM Cool, as of now the 'x' is already present in jenkins markup. Will look into the css option. 

@raderio The issue is now fixed. 

<img width="360" alt="screen shot 2016-02-21 at 00 15 33" src="https://cloud.githubusercontent.com/assets/10304259/13200031/4c3a7e9c-d830-11e5-908c-175a01e7c267.png">

**Closed as completed by aarjithn** 2016-02-21 00:16 UTC
